module.exports = {
  ChangeAvailability: { type: 'object', additionalProperties: false, properties: { evse: { type: 'object', properties: { id: { type: 'integer' }, connectorId: { type: 'integer' } }, required: ['id'] }, operationalStatus: { type: 'string', enum: ['Inoperative', 'Operative'] } }, required: ['operationalStatus'] },
  Reset: { type: 'object', additionalProperties: false, properties: { type: { type: 'string', enum: ['Immediate', 'OnIdle'] }, evseId: { type: 'integer' } }, required: ['type'] },
  UnlockConnector: { type: 'object', additionalProperties: false, properties: { evseId: { type: 'integer' }, connectorId: { type: 'integer' } }, required: ['evseId', 'connectorId'] },
  TriggerMessage: { type: 'object', additionalProperties: false, properties: { requestedMessage: { type: 'string', enum: ['BootNotification', 'LogStatusNotification', 'FirmwareStatusNotification', 'Heartbeat', 'MeterValues', 'SignChargingStationCertificate', 'SignV2GCertificate', 'StatusNotification', 'TransactionEvent', 'SignCombinedCertificate', 'PublishFirmwareStatusNotification'] }, evse: { type: 'object', properties: { id: { type: 'integer' }, connectorId: { type: 'integer' } }, required: ['id'] } }, required: ['requestedMessage'] },
  ReserveNow: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer' }, expiryDateTime: { type: 'string' }, connectorType: { type: 'string', enum: ['cCCS1', 'cCCS2', 'cType1', 'cType2', 'sType2', 'Undetermined', 'Unknown'] }, idToken: { type: 'object', properties: { idToken: { type: 'string' }, type: { type: 'string', enum: ['Central', 'eMAID', 'ISO14443', 'KeyCode', 'Local', 'MacAddress', 'NoAuthorization'] } }, required: ['idToken', 'type'] }, evseId: { type: 'integer' } }, required: ['id', 'expiryDateTime', 'idToken'] },
  SetChargingProfile: { type: 'object', additionalProperties: false, properties: { evseId: { type: 'integer' }, chargingProfile: { type: 'object', properties: { id: { type: 'integer' }, stackLevel: { type: 'integer' }, chargingProfilePurpose: { type: 'string', enum: ['ChargingStationExternalConstraints', 'ChargingStationMaxProfile', 'TxDefaultProfile', 'TxProfile'] }, chargingProfileKind: { type: 'string', enum: ['Absolute', 'Recurring', 'Relative'] }, chargingSchedule: { type: 'array' } }, required: ['id', 'stackLevel', 'chargingProfilePurpose', 'chargingProfileKind', 'chargingSchedule'] } }, required: ['evseId', 'chargingProfile'] },
  RequestStartTransaction: { type: 'object', additionalProperties: false, properties: { evseId: { type: 'integer' }, idToken: { type: 'object', properties: { idToken: { type: 'string' }, type: { type: 'string', enum: ['Central', 'eMAID', 'ISO14443', 'KeyCode', 'Local', 'MacAddress', 'NoAuthorization'] } }, required: ['idToken', 'type'] }, remoteStartId: { type: 'integer' } }, required: ['evseId', 'idToken', 'remoteStartId'] },
  RequestStopTransaction: { type: 'object', additionalProperties: false, properties: { transactionId: { type: 'string' } }, required: ['transactionId'] },
  SetVariables: { type: 'object', additionalProperties: false, properties: { setVariableData: { type: 'array', items: { type: 'object', properties: { attributeValue: { type: 'string' }, component: { type: 'object', properties: { name: { type: 'string' } } }, variable: { type: 'object', properties: { name: { type: 'string' } } } }, required: ['attributeValue', 'component', 'variable'] } } }, required: ['setVariableData'] },
  GetVariables: { type: 'object', additionalProperties: false, properties: { getVariableData: { type: 'array', items: { type: 'object', properties: { component: { type: 'object', properties: { name: { type: 'string' } } }, variable: { type: 'object', properties: { name: { type: 'string' } } } }, required: ['component', 'variable'] } } }, required: ['getVariableData'] },
  GetReport: { type: 'object', additionalProperties: false, properties: { evseId: { type: 'integer' }, reportBase: { type: 'string', enum: ['ConfigurationInventory', 'FullInventory', 'SummaryInventory'] } }, required: [] },
  GetMonitoringReport: { type: 'object', additionalProperties: false, properties: { monitoringBase: { type: 'string', enum: ['All', 'FactoryDefault', 'HardWiredOnly'] } }, required: [] },
  SetVariableMonitoring: { type: 'object', additionalProperties: false, properties: { setMonitoringData: { type: 'array', items: { type: 'object', properties: { value: { type: 'number' }, type: { type: 'string', enum: ['UpperThreshold', 'LowerThreshold', 'Delta'] }, severity: { type: 'integer' }, component: { type: 'object' }, variable: { type: 'object' } }, required: ['value', 'type', 'severity', 'component', 'variable'] } } }, required: ['setMonitoringData'] },
  SetMonitoringBase: { type: 'object', additionalProperties: false, properties: { monitoringBase: { type: 'string', enum: ['All', 'FactoryDefault', 'HardWiredOnly'] } }, required: ['monitoringBase'] },
  SetMonitoringLevel: { type: 'object', additionalProperties: false, properties: { severity: { type: 'integer' } }, required: ['severity'] },
  SetNetworkProfile: { type: 'object', additionalProperties: false, properties: { configurationSlot: { type: 'integer' }, connectionData: { type: 'object' } }, required: ['configurationSlot', 'connectionData'] },
  GetLog: { type: 'object', additionalProperties: false, properties: { log: { type: 'object', properties: { remoteLocation: { type: 'string' }, type: { type: 'string', enum: ['DiagnosticsLog', 'SecurityLog'] } }, required: ['remoteLocation', 'type'] } }, required: ['log'] },
  InstallCertificate: { type: 'object', additionalProperties: false, properties: { certificateType: { type: 'string', enum: ['V2GRootCertificate', 'MORootCertificate', 'CSMSRootCertificate', 'V2GCertificateChain', 'ManufacturerRootCertificate'] }, certificate: { type: 'string' } }, required: ['certificateType', 'certificate'] },
  GetInstalledCertificateIds: { type: 'object', additionalProperties: false, properties: { certificateType: { type: 'array', items: { type: 'string' } } }, required: ['certificateType'] },
  DeleteCertificate: { type: 'object', additionalProperties: false, properties: { certificateHashData: { type: 'object', properties: { hashAlgorithm: { type: 'string', enum: ['SHA256', 'SHA384', 'SHA512'] }, issuerNameHash: { type: 'string' }, issuerKeyHash: { type: 'string' }, serialNumber: { type: 'string' } }, required: ['hashAlgorithm', 'issuerNameHash', 'issuerKeyHash', 'serialNumber'] } }, required: ['certificateHashData'] },
  CertificateSigned: { type: 'object', additionalProperties: false, properties: { certificateChain: { type: 'string' }, typeOfCertificate: { type: 'string', enum: ['V2GRootCertificate', 'MORootCertificate', 'CSMSRootCertificate', 'V2GCertificateChain', 'ManufacturerRootCertificate'] } }, required: ['certificateChain'] },
  GetTransactionStatus: { type: 'object', additionalProperties: false, properties: { transactionId: { type: 'string' }, evseId: { type: 'integer' } }, required: [] },
  CustomerInformation: { type: 'object', additionalProperties: false, properties: { requestId: { type: 'integer' }, report: { type: 'boolean' }, clear: { type: 'boolean' } }, required: ['requestId', 'report', 'clear'] },
  PublishFirmware: { type: 'object', additionalProperties: false, properties: { location: { type: 'string' }, checksum: { type: 'string' }, requestId: { type: 'integer' } }, required: ['location', 'checksum', 'requestId'] },
  UnpublishFirmware: { type: 'object', additionalProperties: false, properties: { checksum: { type: 'string' } }, required: ['checksum'] },
  SignCertificate: { type: 'object', additionalProperties: false, properties: { csr: { type: 'string' }, signingCertificateType: { type: 'string', enum: ['ChargingStationCertificate', 'V2GCertificate'] } }, required: ['csr'] },
  Get15118EVCertificate: { type: 'object', additionalProperties: false, properties: { iso15118SchemaVersion: { type: 'string' }, action: { type: 'string', enum: ['Install', 'Update'] }, exiRequest: { type: 'string' } }, required: ['iso15118SchemaVersion', 'action', 'exiRequest'] },
  GetCertificateStatus: { type: 'object', additionalProperties: false, properties: { ocspRequestData: { type: 'object', properties: { hashAlgorithm: { type: 'string', enum: ['SHA256', 'SHA384', 'SHA512'] }, issuerNameHash: { type: 'string' }, issuerKeyHash: { type: 'string' }, serialNumber: { type: 'string' }, responderURL: { type: 'string' } }, required: ['hashAlgorithm', 'issuerNameHash', 'issuerKeyHash', 'serialNumber', 'responderURL'] } }, required: ['ocspRequestData'] }
};

module.exports.EXTRA_ACTIONS = [
  { name: 'RequestStartTransaction', dir: 'CS→CP', desc: '请求启动交易' },
  { name: 'RequestStopTransaction', dir: 'CS→CP', desc: '请求停止交易' },
  { name: 'SetVariables', dir: 'CS→CP', desc: '设置变量' },
  { name: 'GetVariables', dir: 'CS→CP', desc: '获取变量' },
  { name: 'GetReport', dir: 'CS→CP', desc: '获取设备报告' },
  { name: 'GetMonitoringReport', dir: 'CS→CP', desc: '获取监控报告' },
  { name: 'SetVariableMonitoring', dir: 'CS→CP', desc: '设置变量监控' },
  { name: 'SetMonitoringBase', dir: 'CS→CP', desc: '设置监控基准' },
  { name: 'SetMonitoringLevel', dir: 'CS→CP', desc: '设置监控级别' },
  { name: 'SetNetworkProfile', dir: 'CS→CP', desc: '设置网络配置' },
  { name: 'GetLog', dir: 'CS→CP', desc: '获取日志' },
  { name: 'InstallCertificate', dir: 'CS→CP', desc: '安装证书' },
  { name: 'GetInstalledCertificateIds', dir: 'CS→CP', desc: '获取已安装证书ID' },
  { name: 'DeleteCertificate', dir: 'CS→CP', desc: '删除证书' },
  { name: 'CertificateSigned', dir: 'CS→CP', desc: '证书签名通知' },
  { name: 'GetTransactionStatus', dir: 'CS→CP', desc: '获取交易状态' },
  { name: 'CustomerInformation', dir: 'CS→CP', desc: '客户信息' },
  { name: 'PublishFirmware', dir: 'CS→CP', desc: '发布固件' },
  { name: 'UnpublishFirmware', dir: 'CS→CP', desc: '取消发布固件' },
  { name: 'SignCertificate', dir: 'CP→CS', desc: '签名证书请求' },
  { name: 'Get15118EVCertificate', dir: 'CP→CS', desc: '获取ISO15118证书' },
  { name: 'GetCertificateStatus', dir: 'CP→CS', desc: '获取证书状态' }
];