"""Embed IEC symbol data directly into api/render_svg.js as JS const blocks.

Why this exists:
  - Vercel serverless function bundles don't reliably include api/_iec_symbols_svg/**
    or includeFiles patterns, so runtime FS lookups fail and we fall back to placeholder.
  - Static `import('./_iec_symbols_inline.mjs')` should work but has been observed to
    not actually bundle the .mjs in some Vercel deploys.
  - The most reliable path is to put the data inside the same JS file that uses it,
    so there's literally no extra file dependency.

What it does:
  1. Reads iec_symbols_svg/* + index.json, builds IEC_SYMBOLS_INDEX + IEC_SYMBOLS_FILES.
  2. Replaces the marker `// __INLINE_IEC_DATA__` in api/render_svg.js with the const block.
"""
import os
import re
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_SVG_DIR = ROOT / "iec_symbols_svg"
RENDERER_PATH = ROOT / "api" / "render_svg.js"
MARKER = "// __INLINE_IEC_DATA__"


def extract_inner_svg(svg_text: str, fallback_w: float, fallback_h: float) -> dict:
    m = svg_text.strip()
    vb_match = re.search(r'viewBox="([\d.\s\-]+)"', m)
    vb = vb_match.group(1) if vb_match else f"0 0 {fallback_w} {fallback_h}"
    parts = vb.split()
    try:
        w = float(parts[2]) if len(parts) > 2 else fallback_w
        h = float(parts[3]) if len(parts) > 3 else fallback_h
    except (ValueError, IndexError):
        w = fallback_w
        h = fallback_h
    inner_match = re.search(r'<svg[^>]*>([\s\S]*)</svg>', m)
    inner_svg = inner_match.group(1) if inner_match else m
    if 'xlink:' in inner_svg and 'xmlns:xlink' not in inner_svg:
        inner_svg = inner_svg.replace('<image ', '<image xmlns:xlink="http://www.w3.org/1999/xlink" ', 1)
    return {"w": w, "h": h, "viewBox": vb, "innerSvg": inner_svg}


def main():
    if not SRC_SVG_DIR.is_dir():
        print(f"ERROR: source dir not found: {SRC_SVG_DIR}", file=sys.stderr)
        sys.exit(1)
    if not RENDERER_PATH.is_file():
        print(f"ERROR: renderer not found: {RENDERER_PATH}", file=sys.stderr)
        sys.exit(1)
    if MARKER not in RENDERER_PATH.read_text(encoding="utf-8"):
        print(f"ERROR: marker {MARKER!r} not found in {RENDERER_PATH}", file=sys.stderr)
        sys.exit(1)

    # Load index + files
    index_path = SRC_SVG_DIR / "iec_symbols_index.json"
    if not index_path.is_file():
        print(f"ERROR: index not found: {index_path}", file=sys.stderr)
        sys.exit(1)
    idx = json.loads(index_path.read_text(encoding="utf-8"))

    entries = []
    file_map = {}
    seen_ids = set()
    for sym in idx.get("symbols", []):
        filename = sym["filename"]
        fp = SRC_SVG_DIR / filename
        if not fp.is_file():
            print(f"  SKIP missing: {filename}")
            continue
        text = fp.read_text(encoding="utf-8")
        parsed = extract_inner_svg(text, sym.get("width", 100), sym.get("height", 60))
        sym_id = sym["id"]
        if sym_id in seen_ids:
            sym_id = f"{sym_id}_{filename[:30].replace(' ', '_')}"
        seen_ids.add(sym_id)
        entries.append({
            "id": sym_id,
            "name": sym.get("name_cn") or sym.get("name") or filename,
            "filename": filename,
            "width": parsed["w"],
            "height": parsed["h"],
            "viewBox": parsed["viewBox"],
        })
        file_map[filename] = parsed["innerSvg"]

    print(f"indexed {len(entries)} symbols")

    # Build the const block
    block_lines = []
    block_lines.append("// ============ INLINE IEC SYMBOL DATA (auto-generated by tools/build_inline_renderer.py) ============")
    block_lines.append(f"const IEC_SYMBOLS_INDEX = {json.dumps(entries, ensure_ascii=False)};")
    block_lines.append("const IEC_SYMBOLS_FILES = Object.freeze({")
    for fn, content in file_map.items():
        escaped = content.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        block_lines.append(f"  {json.dumps(fn)}: `{escaped}`,")
    block_lines.append("});")
    block_lines.append("// ============ END INLINE IEC SYMBOL DATA ============")
    block = "\n".join(block_lines)

    # Replace marker
    content = RENDERER_PATH.read_text(encoding="utf-8")
    new_content = content.replace(MARKER, block)
    RENDERER_PATH.write_text(new_content, encoding="utf-8")

    size_kb = RENDERER_PATH.stat().st_size / 1024
    print(f"wrote {RENDERER_PATH} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()