"""Build inline IEC symbol module.

Reads iec_symbols_svg/*.svg and iec_symbols_svg/iec_symbols_index.json,
emits a single ES module (api/_iec_symbols_inline.mjs) with:
  - IEC_SYMBOLS_INDEX: array of symbol metadata
  - IEC_SYMBOLS_FILES: { filename: <svg string>, ... }

This avoids relying on Vercel bundling api/_iec_symbols_svg/** into the
function bundle (which has been unreliable across Vercel versions).
"""
import os
import re
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "iec_symbols_svg"
OUT_FILE = ROOT / "api" / "_iec_symbols_inline.mjs"


def extract_inner_svg(svg_text: str, fallback_w: float, fallback_h: float) -> dict:
    """Parse an IEC SVG file and return { w, h, viewBox, innerSvg, name }."""
    m = svg_text.strip()
    # viewBox
    vb_match = re.search(r'viewBox="([\d.\s\-]+)"', m)
    vb = vb_match.group(1) if vb_match else f"0 0 {fallback_w} {fallback_h}"
    parts = vb.split()
    try:
        w = float(parts[2]) if len(parts) > 2 else fallback_w
        h = float(parts[3]) if len(parts) > 3 else fallback_h
    except (ValueError, IndexError):
        w = fallback_w
        h = fallback_h
    inner_match = re.search(r'<svg[^>]*>([\s\S]*)</svg>', m)
    inner_svg = inner_match.group(1) if inner_match else m
    # Ensure xmlns:xlink is preserved (some symbols use xlink:href)
    if 'xlink:' in inner_svg and 'xmlns:xlink' not in inner_svg:
        inner_svg = inner_svg.replace('<image ', '<image xmlns:xlink="http://www.w3.org/1999/xlink" ', 1)
    return {"w": w, "h": h, "viewBox": vb, "innerSvg": inner_svg}


def main():
    if not SRC_DIR.is_dir():
        print(f"ERROR: source dir not found: {SRC_DIR}", file=sys.stderr)
        sys.exit(1)

    # Load index
    index_path = SRC_DIR / "iec_symbols_index.json"
    if index_path.is_file():
        idx = json.loads(index_path.read_text(encoding="utf-8"))
    else:
        print("WARN: iec_symbols_index.json not found, scanning directory")
        idx = {"symbols": []}

    # Build entries
    entries = []
    file_map = {}
    seen_ids = set()
    for sym in idx.get("symbols", []):
        filename = sym["filename"]
        fp = SRC_DIR / filename
        if not fp.is_file():
            print(f"  SKIP missing: {filename}")
            continue
        try:
            text = fp.read_text(encoding="utf-8")
        except Exception as e:
            print(f"  ERR {filename}: {e}")
            continue
        parsed = extract_inner_svg(text, sym.get("width", 100), sym.get("height", 60))
        sym_id = sym["id"]
        if sym_id in seen_ids:
            # Duplicate id — append filename suffix to disambiguate
            sym_id = f"{sym_id}_{filename[:30].replace(' ', '_')}"
        seen_ids.add(sym_id)
        entries.append({
            "id": sym_id,
            "name": sym.get("name_cn") or sym.get("name") or filename,
            "filename": filename,
            "width": parsed["w"],
            "height": parsed["h"],
            "viewBox": parsed["viewBox"],
        })
        file_map[filename] = parsed["innerSvg"]

    print(f"indexed {len(entries)} symbols")

    # Emit module
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUT_FILE.open("w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/build_inline_iec_symbols.py — do not edit by hand.\n")
        f.write("// Run `python tools/build_inline_iec_symbols.py` to regenerate after editing iec_symbols_svg/.\n\n")
        f.write("export const IEC_SYMBOLS_INDEX = ")
        # Serialize index entries (without innerSvg — that's in the files map)
        f.write(json.dumps(entries, ensure_ascii=False, indent=2))
        f.write(";\n\n")
        f.write("// Map: filename -> raw inner <svg> contents (excluding outer <svg> wrapper).\n")
        f.write("// This avoids filesystem IO at runtime and works on any serverless platform.\n")
        f.write("export const IEC_SYMBOLS_FILES = Object.freeze({\n")
        # Write each file as a string literal
        for fn, content in file_map.items():
            # Escape backticks, backslashes, and $ (template-literal interpolation)
            escaped = content.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
            # Single-quoted key with double-quoted string value
            f.write(f"  {json.dumps(fn)}: `{escaped}`,\n")
        f.write("});\n")
    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"wrote {OUT_FILE} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()